export const SocketNames = {
  CANVAS_CLEARED: 'canvas_cleared',
  CLEAR_CANVAS: 'clear_canvas',
  DISPATCH_CANVAS_STATE: 'dispatch_canvas_state',
  DRAW_POINT: 'draw_point',
  DRAW_ERASER: 'draw_eraser',
  GET_CANVAS_STATE: 'get_canvas_state',
  REQUEST_CANVAS_STATE: 'request_canvas_state',
  SEND_CANVAS_STATE: 'send_canvas_state',
  UPDATE_CANVAS_STATE: 'update_canvas_state',
  SEND_NOTIFICATION: 'send_notification',
  UPDATE_ROOM: 'update_room',
  DELETE_ROOM: 'delete_room',
  KICK_USER: 'kick_user',
  KICK_REQUEST: 'kick_request',
  USER_JOINED: 'user_joined',
} as const;
