export enum Services {
  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
  GATEWAY_ROOMS_MANAGER = 'GATEWAY_ROOMS_MANAGER',
  ROOMS_SERVICE = 'ROOMS_SERVICE',
  USERS_SERVICE = 'USERS_SERVICE',
  PASSWORDS_SERVICE = 'PASSWORDS_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
}

export enum Events {
  ROOM_DELETE_EVENT = 'room.delete',
}
